name: Code Formatting

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        submodules: true
    - name: Install ReSharper
      run: |
        cd csharp
        dotnet tool install -g JetBrains.ReSharper.GlobalTools --version 2022.2.2

    - name: Restore
      run: |
        cd csharp
        dotnet restore ArmoniK.Utils.sln

    - name: Reformat
      run: |
        cd csharp
        jb cleanupcode ArmoniK.Utils.sln

    - name: Check Diff
      id: check-diff
      run: |
        cd csharp
        DIFF="$(git diff --name-only)"

        if [ -z "$DIFF" ]; then
          echo "OK: Format is clean"
        else
          echo "Error: Format was not clean"
          echo "List of files:"
          echo "$DIFF"
          git diff
          exit 1
        fi
    - name: Generate patch
      if: ${{ failure() && steps.check-diff.conclusion == 'failure' }}
      run: |
        git diff > patch-csharp.diff
    - uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3
      if: ${{ failure() && steps.check-diff.conclusion == 'failure' }}
      with:
        name: patch-csharp
        path: ./patch-csharp.diff
