name: Deploy

on:
  push:
    branches: [ '**' ]

jobs:


 versionning:
    name: Versionning
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.genver.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Generate Version
      id: genver
      run: |
        VERSION=$(docker run --rm -v $(pwd):/repo codacy/git-version /bin/git-version --folder=/repo --release-branch=${{ github.ref_name }}-pre --dev-branch=main)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "VERSION : $VERSION"
        echo "Version :" >> $GITHUB_STEP_SUMMARY
        echo "$VERSION" >> $GITHUB_STEP_SUMMARY

 build: 
    runs-on: ubuntu-latest
    needs:
      - versionning
    env:
      GENVERSION: ${{ needs.versionning.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        submodules: true

    - name: Build the package
      run: |
         cd csharp
         dotnet build ArmoniK.Utils.sln -c Release

    - name: Pack the package VERSION
      run: |
        cd csharp
        dotnet pack ArmoniK.Utils.sln -c Release -o /tmp/packages -p:Version=$GENVERSION
        
    - name: Push the package
      run: |
        cd csharp
        find /tmp/packages -name 'ArmoniK*.nupkg' ! -name '*test*.nupkg' -exec dotnet nuget push /tmp/packages/ArmoniK.Utils.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols \;

 test: 
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      
    - name: Run tests
      run: |
        cd csharp
        dotnet test --runtime linux-x64 -f net6.0 --logger "trx;LogFileName=test-results.trx"
  
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: IntegrationTests
        path: ./csharp/tests/TestResults/test-results.trx
        reporter: dotnet-trx
        
